#!/usr/bin/env python
import argparse
from alibuild_helpers.doctor import doDoctor, doctorArgParser

if __name__ == "__main__":
  parser = doctorArgParser(argparse.ArgumentParser())
  args = parser.parse_args()
  doDoctor(args, parser)

