#!/usr/bin/env python3
import sys
import os
from os.path import dirname, join, abspath
if __name__ == "__main__":
  bitsBuild = join(dirname(abspath(sys.argv[0])), "bitsBuild")
  os.execv(bitsBuild, [ bitsBuild, "doctor" ] + sys.argv[1:])
