#!/usr/bin/env python3
import sys
import os
from os.path import dirname, join, abspath
if __name__ == "__main__":
  aliBuild = join(dirname(abspath(sys.argv[0])), "aliBuild")
  os.execv(aliBuild, [ aliBuild, "doctor" ] + sys.argv[1:])
